version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    expose:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  demo-mysql:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_DATABASE: 'demo'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'demo_user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'demo_pass'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3307:3306"
    volumes:
      - demo-mysql:/var/lib/mysql

  labproject:
    build: .
    volumes:
      - /data/labproject
    ports:
      - "8080:8080"
    depends_on:
      - demo-mysql
      - kafka
      - zookeeper
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://demo-mysql:3306/demo
      SPRING_DATASOURCE_USERNAME: demo_user
      SPRING_DATASOURCE_PASSWORD: demo_pass

  my-consumer-logs:
    build: ./my-consumer-logs
    depends_on:
      - kafka
    ports:
      - "8081:8081"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  my-consumer-events:
    build: ./my-consumer-events
    depends_on:
      - kafka
    ports:
      - "8082:8082"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

volumes:
  demo-mysql:

